spring.application.name=projeto-interdisciplinar

# ===================================
# CONFIGURAÇÕES DA APLICAÇÃO (Spring Web)
# ===================================
server.port=8080
server.servlet.context-path=/api

# ===================================
# CONEXÃO COM O SQL SERVER (JDBC)
# ===================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MeuBanco;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
#Comando docker da conexão ao banco
#docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Girassol123@" -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2022-latest
spring.datasource.password=Girassol123@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===================================
# Dialeto específico para o SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Exibe as queries SQL executadas no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
